/**
 * prompt-library-data.ts — third-party prompt library loader.
 *
 * Pulls curated image-generation prompts from public GitHub collections,
 * parses each repo's README or structured JSON into typed
 * entries, and serves keyword/category/tag-filtered pages to the dialog.
 *
 * Caching: parsed items go to versioned localStorage
 * with a 1-hour TTL; oversized/quota failures degrade silently to
 * per-session memory. Unreachable sources retain their bundled baseline.
 */

import bundledSnapshot from "./prompt-library-snapshot.json";

export type LibraryPrompt = {
  id: string;
  title: string;
  coverUrl: string;
  prompt: string;
  tags: string[];
  category: string;
  githubUrl: string;
  sourceLabel?: string;
  sourceUrl?: string;
};

export type PromptPage = {
  items: LibraryPrompt[];
  tags: string[];
  categories: string[];
  total: number;
};

export const ALL_PROMPTS_OPTION = "全部";

// A new source must appear immediately, even with a fresh pre-upgrade cache.
const CACHE_KEY = "nexu:canvas:prompt-cache:v2";
const CACHE_TTL_MS = 1000 * 60 * 60;

const AWESOME_GPT_IMAGE =
  "https://raw.githubusercontent.com/ZeroLu/awesome-gpt-image/main";
const AWESOME_GPT4O =
  "https://raw.githubusercontent.com/ImgEdify/Awesome-GPT4o-Image-Prompts/main";
const YOUMIND_GPT_IMAGE_2 =
  "https://raw.githubusercontent.com/YouMind-OpenLab/awesome-gpt-image-2/main";
const YOUMIND_NANO_BANANA =
  "https://raw.githubusercontent.com/YouMind-OpenLab/awesome-nano-banana-pro-prompts/main";
const DAVIDWU_GPT_IMAGE2 =
  "https://raw.githubusercontent.com/davidwuw0811-boop/awesome-gpt-image2-prompts/main";
const FREESTYLEFLY_GPT_IMAGE_2 =
  "https://raw.githubusercontent.com/freestylefly/awesome-gpt-image-2/main";
const FREESTYLEFLY_REPO = "https://github.com/freestylefly/awesome-gpt-image-2";
type SourcePrompt = Omit<LibraryPrompt, "category" | "githubUrl"> & {
  githubUrl?: string;
};

type CategorySource = {
  category: string;
  githubUrl: string;
  load: () => Promise<SourcePrompt[]>;
};

const SOURCES: CategorySource[] = [
  {
    category: "freestylefly-gpt-image-2",
    githubUrl: FREESTYLEFLY_REPO,
    load: async () =>
      parseFreestyleflyCases(
        JSON.parse(
          await fetchText(FREESTYLEFLY_GPT_IMAGE_2, "data/cases.json"),
        ),
      ),
  },
  {
    category: "awesome-gpt-image",
    githubUrl: "https://github.com/ZeroLu/awesome-gpt-image",
    load: loadAwesomeGptImage,
  },
  {
    category: "awesome-gpt4o-image-prompts",
    githubUrl: "https://github.com/ImgEdify/Awesome-GPT4o-Image-Prompts",
    load: loadAwesomeGpt4o,
  },
  {
    category: "youmind-gpt-image-2",
    githubUrl: "https://github.com/YouMind-OpenLab/awesome-gpt-image-2",
    load: () =>
      loadYouMind(YOUMIND_GPT_IMAGE_2, "youmind-gpt-image-2", "gpt-image-2"),
  },
  {
    category: "youmind-nano-banana-pro",
    githubUrl:
      "https://github.com/YouMind-OpenLab/awesome-nano-banana-pro-prompts",
    load: () =>
      loadYouMind(
        YOUMIND_NANO_BANANA,
        "youmind-nano-banana-pro",
        "nano-banana-pro",
      ),
  },
  {
    category: "davidwu-gpt-image2-prompts",
    githubUrl:
      "https://github.com/davidwuw0811-boop/awesome-gpt-image2-prompts",
    load: loadDavidWu,
  },
];

export function promptCategories(): string[] {
  return SOURCES.map((s) => s.category);
}

// ── Fetch orchestration + cache ────────────────────────────────────────────
//
// Freshness ladder:
//   1. memory / localStorage cache within TTL → serve as-is
//   2. stale cache OR nothing → serve IMMEDIATELY (stale cache, else the
//      bundled snapshot) and kick off a background refresh — opening the
//      dialog never blocks on GitHub fetches
//   3. refreshed data lands in the caches; the next query serves it

/** Built-in baseline (generated by apps/web/scripts/generate-prompt-snapshot.ts). */
const SNAPSHOT: LibraryPrompt[] = bundledSnapshot as LibraryPrompt[];

let memoryCache: LibraryPrompt[] | null = null;
let memoryCacheAt = 0;
let inFlight: Promise<LibraryPrompt[]> | null = null;

async function getAllPrompts(): Promise<LibraryPrompt[]> {
  const now = Date.now();
  if (memoryCache && now - memoryCacheAt < CACHE_TTL_MS) return memoryCache;

  const stored = readStoredCache();
  if (stored) {
    memoryCache = stored.items;
    memoryCacheAt = stored.fetchedAt;
    if (now - stored.fetchedAt < CACHE_TTL_MS) return stored.items;
  }

  // Nothing fresh: refresh in the background, serve what we have right now.
  if (!inFlight) {
    inFlight = refreshFromSources().finally(() => {
      inFlight = null;
    });
  }
  if (stored) return stored.items;
  return SNAPSHOT;
}

async function refreshFromSources(): Promise<LibraryPrompt[]> {
  const live = await loadAllSources({ fallbackToSnapshot: false });
  // A total network failure yields []; don't poison the cache with it, so
  // the next open retries instead of serving an empty library for an hour.
  if (live.length === 0) return [];
  const items = promptCategories().flatMap((category) => {
    const refreshed = live.filter((item) => item.category === category);
    return refreshed.length > 0
      ? refreshed
      : SNAPSHOT.filter((item) => item.category === category);
  });
  memoryCache = items;
  memoryCacheAt = Date.now();
  writeStoredCache(items, memoryCacheAt);
  return items;
}

/**
 * Fetch + parse every source (exported for the snapshot generation script).
 * Failed sources keep their bundled entries. Snapshot generation disables
 * fallback so a fetch failure cannot masquerade as a successful update.
 */
export async function loadAllSources({
  categories = promptCategories(),
  fallbackToSnapshot = true,
}: { categories?: string[]; fallbackToSnapshot?: boolean } = {}): Promise<
  LibraryPrompt[]
> {
  const settled = await Promise.all(
    SOURCES.filter((source) => categories.includes(source.category)).map(
      async (source) => {
        try {
          const items = await source.load();
          if (items.length === 0) throw new Error("Empty prompt source");
          return items.map((item) => ({
            ...item,
            category: source.category,
            githubUrl: item.githubUrl ?? source.githubUrl,
          }));
        } catch {
          return fallbackToSnapshot
            ? SNAPSHOT.filter((item) => item.category === source.category)
            : [];
        }
      },
    ),
  );
  return settled.flat();
}

function readStoredCache(): {
  items: LibraryPrompt[];
  fetchedAt: number;
} | null {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as {
      items?: LibraryPrompt[];
      fetchedAt?: number;
    };
    if (!Array.isArray(parsed.items) || typeof parsed.fetchedAt !== "number") {
      return null;
    }
    return { items: parsed.items, fetchedAt: parsed.fetchedAt };
  } catch {
    return null;
  }
}

function writeStoredCache(items: LibraryPrompt[], fetchedAt: number): void {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify({ items, fetchedAt }));
  } catch {
    // Quota exceeded on a large payload — memory cache still covers the session.
  }
}

// ── Query API (dialog-facing) ──────────────────────────────────────────────

export async function fetchPromptPage({
  keyword = "",
  tags = [],
  category = ALL_PROMPTS_OPTION,
  page = 1,
  pageSize = 20,
}: {
  keyword?: string;
  tags?: string[];
  category?: string;
  page?: number;
  pageSize?: number;
} = {}): Promise<PromptPage> {
  const items = await getAllPrompts();
  const query = keyword.trim().toLowerCase();
  const safePage = Math.max(1, page);
  const safeSize = Math.max(1, Math.min(100, pageSize));
  // Tag options come from the keyword+category slice WITHOUT the tag filter,
  // so picking one tag doesn't collapse the tag cloud to itself.
  const scope = applyFilters(items, {
    keyword: query,
    category,
    tags: [],
    deduplicate: false,
  });
  const filtered = applyFilters(items, { keyword: query, category, tags });
  return {
    items: filtered.slice((safePage - 1) * safeSize, safePage * safeSize),
    tags: uniqueTags(scope),
    categories: promptCategories(),
    total: filtered.length,
  };
}

export function applyFilters(
  items: ReadonlyArray<LibraryPrompt>,
  options: {
    keyword: string;
    category: string;
    tags: string[];
    deduplicate?: boolean;
  },
): LibraryPrompt[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (
      options.category &&
      options.category !== ALL_PROMPTS_OPTION &&
      item.category !== options.category
    ) {
      return false;
    }
    if (
      options.tags.length > 0 &&
      !options.tags.some((tag) => item.tags.includes(tag))
    ) {
      return false;
    }
    if (
      options.keyword &&
      ![item.title, item.prompt, item.category, ...item.tags]
        .join(" ")
        .toLowerCase()
        .includes(options.keyword)
    )
      return false;
    // Keep each collection intact; collapse identical prompts only in 全部.
    if (
      options.deduplicate !== false &&
      (!options.category || options.category === ALL_PROMPTS_OPTION)
    ) {
      const key = item.prompt.trim().replace(/\s+/g, " ");
      if (seen.has(key)) return false;
      seen.add(key);
    }
    return true;
  });
}

function uniqueTags(items: ReadonlyArray<LibraryPrompt>): string[] {
  return Array.from(new Set(items.flatMap((i) => i.tags).filter(Boolean)));
}

// ── Per-source loaders ─────────────────────────────────────────────────────

const FREESTYLEFLY_CATEGORIES: Record<string, string> = {
  "Architecture & Spaces": "建筑与空间",
  "Brand & Logos": "品牌与标志",
  "Characters & People": "角色与人物",
  "Charts & Infographics": "图表与信息图",
  "Documents & Publishing": "文档与出版",
  "History & Classical Themes": "历史与古典",
  "Illustration & Art": "插画与艺术",
  "Other Use Cases": "其他创意",
  "Photography & Realism": "摄影与写实",
  "Posters & Typography": "海报与排版",
  "Products & E-commerce": "产品与电商",
  "Scenes & Storytelling": "场景与叙事",
  "UI & Interfaces": "UI与界面",
};

function httpUrl(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  try {
    const url = new URL(value);
    return url.protocol === "https:" || url.protocol === "http:"
      ? url.href
      : undefined;
  } catch {
    return undefined;
  }
}

/** cases.json uses website image paths; the actual files live in data/images. */
export function parseFreestyleflyCases(data: unknown): SourcePrompt[] {
  if (
    !data ||
    typeof data !== "object" ||
    !("cases" in data) ||
    !Array.isArray(data.cases)
  )
    return [];
  const items: SourcePrompt[] = [];
  const seen = new Set<number>();
  for (const row of data.cases as unknown[]) {
    if (!row || typeof row !== "object") continue;
    const item = row as Record<string, unknown>;
    if (
      typeof item.id !== "number" ||
      !Number.isSafeInteger(item.id) ||
      item.id <= 0 ||
      seen.has(item.id)
    )
      continue;
    const title = typeof item.title === "string" ? item.title.trim() : "";
    const prompt = typeof item.prompt === "string" ? item.prompt.trim() : "";
    if (!title || !prompt) continue;
    const category = typeof item.category === "string" ? item.category : "";
    const tags = [
      category ? (FREESTYLEFLY_CATEGORIES[category] ?? category) : "",
      "gpt-image-2",
    ];
    for (const values of [item.styles, item.scenes]) {
      if (!Array.isArray(values)) continue;
      tags.push(
        ...values
          .filter(
            (v): v is string => typeof v === "string" && Boolean(v.trim()),
          )
          .map((v) => v.trim().toLowerCase()),
      );
    }
    const image = typeof item.image === "string" ? item.image : "";
    // Restrict relative paths to the known repository image directory.
    const coverUrl = /^\/images\/[\w/-]+\.(?:jpg|jpeg|png|webp)$/i.test(image)
      ? `${FREESTYLEFLY_GPT_IMAGE_2}/data${image}`
      : (httpUrl(image) ?? "");
    items.push({
      id: `freestylefly-gpt-image-2-${padId(item.id)}`,
      title,
      prompt,
      coverUrl,
      tags: [...new Set(tags.filter(Boolean))],
      githubUrl: `${FREESTYLEFLY_REPO}/blob/main/docs/gallery-part-${item.id <= 165 ? 1 : 2}.md#case-${item.id}`,
      ...(typeof item.sourceLabel === "string"
        ? { sourceLabel: item.sourceLabel.trim() }
        : {}),
      ...(httpUrl(item.sourceUrl)
        ? { sourceUrl: httpUrl(item.sourceUrl) }
        : {}),
    });
    seen.add(item.id);
  }
  return items;
}

async function loadAwesomeGptImage() {
  const markdown = await fetchText(AWESOME_GPT_IMAGE, "README.zh-CN.md");
  const items: Array<Omit<LibraryPrompt, "category" | "githubUrl">> = [];
  for (const section of splitAtHeading(markdown, "## ")) {
    const tags = headingTags(matchFirst(section, /^##\s+(.+)$/m));
    for (const block of splitAtHeading(section, "### ")) {
      const title = matchFirst(block, /^###\s+(.+)$/m)
        .replace(/\[([^\]]+)]\([^)]+\)/g, "$1")
        .trim();
      const prompt = matchFirst(
        block,
        /\*\*提示词:\*\*\s*\r?\n\s*```[\w-]*\r?\n(.*?)\r?\n```/s,
      ).trim();
      if (!title || !prompt) continue;
      const images = markdownImages(AWESOME_GPT_IMAGE, block);
      items.push({
        id: `awesome-gpt-image-${padId(items.length + 1)}`,
        title,
        prompt,
        coverUrl: images[0] ?? "",
        tags,
      });
    }
  }
  return items;
}

async function loadAwesomeGpt4o() {
  const markdown = await fetchText(AWESOME_GPT4O, "README.zh-CN.md");
  const items: Array<Omit<LibraryPrompt, "category" | "githubUrl">> = [];
  for (const block of splitAtHeading(markdown, "### ")) {
    const title = matchFirst(block, /^###\s+(.+)$/m).trim();
    const prompt = matchFirst(
      block,
      /- \*\*提示词文本：\*\*\s*`(.*?)`/s,
    ).trim();
    if (!title || !prompt) continue;
    const images = markdownImages(AWESOME_GPT4O, block);
    items.push({
      id: `awesome-gpt4o-image-prompts-${padId(items.length + 1)}`,
      title,
      prompt,
      coverUrl: images[0] ?? "",
      tags: ["gpt4o"],
    });
  }
  return items;
}

async function loadYouMind(
  baseUrl: string,
  idPrefix: string,
  modelTag: string,
) {
  const markdown = await fetchText(baseUrl, "README_zh.md");
  const items: Array<Omit<LibraryPrompt, "category" | "githubUrl">> = [];
  for (const block of splitAtHeading(markdown, "### ")) {
    const title = matchFirst(block, /^###\s+No\.\s*\d+:\s*(.+)$/m).trim();
    const prompt = matchFirst(
      block,
      /#### .*?提示词\s*\r?\n\s*```[\w-]*\r?\n(.*?)\r?\n```/s,
    ).trim();
    if (!title || !prompt) continue;
    const images = markdownImages(baseUrl, block);
    const [, titlePrefix] = title.match(/^(.+?) - /) ?? [];
    items.push({
      id: `${idPrefix}-${padId(items.length + 1)}`,
      title,
      prompt,
      coverUrl: images[0] ?? "",
      tags: [modelTag, ...headingTags(titlePrefix ?? "")],
    });
  }
  return items;
}

async function loadDavidWu() {
  const raw = await fetchText(DAVIDWU_GPT_IMAGE2, "prompts.json");
  const data = JSON.parse(raw) as Array<{
    id?: number;
    title_en?: string;
    title_cn?: string;
    category?: string;
    category_cn?: string;
    prompt?: string;
    author?: string;
    source?: string;
    needs_ref?: boolean;
    image?: string;
  }>;
  const items: Array<Omit<LibraryPrompt, "category" | "githubUrl">> = [];
  for (const [index, item] of data.entries()) {
    const title = (item.title_cn || item.title_en || "").trim();
    const prompt = (item.prompt || "").trim();
    if (!title || !prompt) continue;
    const tags = splitTags(
      [item.category_cn, item.category, item.author, item.source]
        .filter(Boolean)
        .join("/"),
      /\//,
    );
    if (item.needs_ref) tags.push("需要参考图");
    items.push({
      id: `davidwu-gpt-image2-prompts-${padId(item.id ?? index + 1)}`,
      title,
      prompt,
      coverUrl: absoluteImageUrl(DAVIDWU_GPT_IMAGE2, item.image ?? ""),
      tags,
    });
  }
  return items;
}

// ── Parsing helpers (exported for tests) ──────────────────────────────────

async function fetchText(baseUrl: string, file: string): Promise<string> {
  const response = await fetch(`${baseUrl}/${file}`, { cache: "no-store" });
  if (!response.ok) throw new Error(`${file} 拉取失败`);
  return response.text();
}

/** Split markdown into blocks, each starting at a line with `prefix`. */
export function splitAtHeading(markdown: string, prefix: string): string[] {
  const blocks: string[] = [];
  let current: string[] = [];
  for (const line of markdown.split("\n")) {
    if (line.startsWith(prefix) && current.length > 0) {
      blocks.push(current.join("\n"));
      current = [];
    }
    current.push(line);
  }
  blocks.push(current.join("\n"));
  return blocks;
}

export function matchFirst(value: string, pattern: RegExp): string {
  return pattern.exec(value)?.[1] ?? "";
}

/**
 * All markdown image URLs in a block, made absolute against the repo base.
 * Badge/shield images (repo decoration, not prompt covers) are dropped —
 * without this, blocks that open with a shields.io badge get a badge as
 * their card cover.
 */
export function markdownImages(baseUrl: string, markdown: string): string[] {
  return Array.from(markdown.matchAll(/!\[[^\]]*]\(([^)]+)\)/g), (match) =>
    absoluteImageUrl(baseUrl, match[1] ?? ""),
  ).filter((url) => url !== "" && !isBadgeImage(url));
}

/** True for badge/shield decoration images that must not be used as covers. */
export function isBadgeImage(url: string): boolean {
  return /img\.shields\.io|badge\.fury\.io|\/badge\//i.test(url);
}

/**
 * Hosts whose covers the controller cover-cache proxy will fetch. Everything
 * the five sources actually reference today; anything else is served direct
 * from its origin (and falls back to the placeholder on error).
 */
export function isProxyableCoverUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== "https:") return false;
    // pbs.twimg.com is deliberately NOT proxied: it is frequently unreachable
    // from the controller's network, and a hanging proxied fetch occupies one
    // of the browser's ~6 connections to OUR origin — a page of covers can
    // starve every other cover/probe request into an endless blank pending
    // state. Loaded direct, a twimg failure stays on twitter's origin pool.
    return (
      parsed.hostname === "github.com" ||
      parsed.hostname.endsWith(".githubusercontent.com")
    );
  } catch {
    return false;
  }
}

/**
 * The <img src> for a cover: proxyable hosts route through the controller's
 * disk-backed cover cache (served from OUR server, one upstream fetch per
 * image ever); other hosts load direct. Returns "" for no cover.
 */
export function promptCoverPath(coverUrl: string): string {
  if (!coverUrl) return "";
  if (!isProxyableCoverUrl(coverUrl)) return coverUrl;
  return `/api/v1/media/prompt-cover?url=${encodeURIComponent(coverUrl)}`;
}

export function absoluteImageUrl(baseUrl: string, image: string): string {
  if (!image) return "";
  if (/^https?:\/\//i.test(image)) return image;
  return `${baseUrl}/${image.replace(/^\.?\//, "")}`;
}

/** Tags from a section heading: strip decoration, split on /&、与. */
export function headingTags(heading: string): string[] {
  return splitTags(
    heading.replace(/[^\p{L}\p{N}/&、与 ]/gu, ""),
    /\s*(?:\/|&|、|与)\s*/,
  );
}

export function splitTags(value: string, pattern: RegExp): string[] {
  return value
    .split(pattern)
    .map((tag) => tag.trim().toLowerCase())
    .filter(Boolean);
}

function padId(value: number): string {
  return String(value).padStart(4, "0");
}

/** Test-only: clear in-memory cache so fetch paths re-run. */
export function __resetPromptDataForTests(): void {
  memoryCache = null;
  memoryCacheAt = 0;
  inFlight = null;
}
