import { isImeComposing } from "@/lib/keyboard";
import { useQuery } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { getApiV1Devices } from "../../../../lib/api/sdk.gen";
import { StatusPill, type StatusTone } from "../a2ui-status";
import type { CustomComponentProps } from "./registry";
import {
  clearPostImageGeneration,
  completePostImageGeneration,
  getBatch,
  setRowStatus,
  startPostImageGeneration,
  updatePost,
  useBatch,
} from "./xhs-batch-store";
import {
  type XHSImageGenerationRequest,
  generateXhsImages,
} from "./xhs-image-generation";
import { XHSImageGenerationPlaceholders } from "./xhs-image-generation-placeholders";
import { XHSImageGenerationPopover } from "./xhs-image-generation-popover";
import { mergeXhsImages } from "./xhs-image-state";
import {
  type XHSPublishResultItem,
  XhsPublishStatusUnknownError,
  publishXhsPost,
  reportXhsPublishResults,
} from "./xhs-publish";

interface XHSEditorProps extends CustomComponentProps {}

interface XHSCompData {
  title?: string;
  content?: string;
  images?: string[];
  hashtags?: string[];
  maxTitleLength?: number;
  /** Set when opened from the batch table → edits/status mirror to the store. */
  batchId?: string;
  postId?: string;
  /** The post's already-assigned device (batch mode). Seeds the selector so
   * opening the editor never silently reassigns the post to another phone. */
  deviceId?: string;
  pendingImageSlots?: string[];
}

type PublishStatus =
  | { state: "idle" }
  | { state: "publishing"; step: string }
  | { state: "success" }
  | { state: "unknown"; message: string }
  | { state: "error"; message: string };

const PUBLISH_TONE: Record<PublishStatus["state"], StatusTone> = {
  idle: "idle",
  publishing: "running",
  success: "done",
  unknown: "blocked",
  error: "failed",
};

export function XHSEditor({ comp, onAction }: XHSEditorProps) {
  const data = comp as unknown as XHSCompData;
  const initialTitle = data.title ?? "";
  const initialContent = data.content ?? "";
  const initialImages: string[] = data.images ?? [];
  const initialHashtags: string[] = data.hashtags ?? [];
  const incomingImages = data.images;
  const maxTitleLength: number = data.maxTitleLength ?? 20;
  const initialDeviceId: string = data.deviceId ?? "";
  const batchId = data.batchId;
  const postId = data.postId;
  const bound = Boolean(batchId && postId);
  const { posts: sharedPosts } = useBatch(
    batchId ?? "__standalone-xhs-editor__",
  );
  const sharedPost = bound
    ? sharedPosts.find((post) => post.id === postId)
    : undefined;

  // Local state
  const [title, setTitle] = useState(initialTitle);
  const [content, setContent] = useState(initialContent);
  const [images, setImages] = useState<string[]>(initialImages);
  const [hashtags, setHashtags] = useState<string[]>(initialHashtags);
  const [newTag, setNewTag] = useState("");
  const [deviceId, setDeviceId] = useState<string>(initialDeviceId);
  const [publish, setPublish] = useState<PublishStatus>({ state: "idle" });
  const [imageGenerationOpen, setImageGenerationOpen] = useState(false);
  const [pendingImageSlots, setPendingImageSlots] = useState<string[]>(
    data.pendingImageSlots ?? [],
  );
  const fileInputRef = useRef<HTMLInputElement>(null);
  const imageGenerationAnchorRef = useRef<HTMLButtonElement>(null);
  const tagInputRef = useRef<HTMLInputElement>(null);

  // A later render_a2ui call with the same surfaceId updates this mounted
  // editor. Preserve local uploads while incorporating media generated by the
  // agent and supplied through the refreshed component definition.
  useEffect(() => {
    if (bound || !incomingImages?.length) return;
    setImages((current) => mergeXhsImages(current, incomingImages));
  }, [bound, incomingImages]);

  // Batch binding: mirror every local edit back to the shared store so the
  // inline table row reflects edits in real time.
  useEffect(() => {
    if (bound && batchId && postId) {
      updatePost(batchId, postId, {
        title,
        content,
        hashtags,
        deviceId,
      });
    }
  }, [bound, batchId, postId, title, content, hashtags, deviceId]);

  const displayedImages = sharedPost?.images ?? images;
  const displayedPendingImageSlots =
    sharedPost?.pendingImageSlots ?? pendingImageSlots;

  const updateImages = (updater: (current: string[]) => string[]) => {
    if (bound && batchId && postId) {
      const latestImages =
        getBatch(batchId).posts.find((post) => post.id === postId)?.images ??
        [];
      updatePost(batchId, postId, { images: updater(latestImages) });
      return;
    }
    setImages(updater);
  };

  // Online devices for publishing. Every listed device is connected, so the
  // list itself is the "online" set; default to the first one.
  const { data: devicesData } = useQuery({
    queryKey: ["devices"],
    queryFn: async () => {
      const { data: d, error } = await getApiV1Devices();
      if (error || !d) throw new Error("设备列表加载失败");
      return d;
    },
    refetchInterval: 10_000,
  });
  const devices = devicesData?.devices ?? [];
  useEffect(() => {
    // In batch mode the table row owns device assignment (seeded via
    // `initialDeviceId`); never auto-pick the first device, or opening the
    // editor would silently reassign every post to devices[0]. Only default in
    // standalone use, where the editor is the sole place to choose a device.
    if (bound) return;
    if (!deviceId && devices.length > 0) {
      setDeviceId(devices[0]?.deviceId ?? "");
    }
  }, [bound, deviceId, devices]);

  // Image upload handler (local FileReader, no server upload)
  const handleImageUpload = (files: FileList | null) => {
    if (!files) return;
    for (const file of Array.from(files)) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const dataUrl = e.target?.result as string;
        updateImages((prev) => [...prev, dataUrl]);
      };
      reader.readAsDataURL(file);
    }
  };

  // Remove image by URL
  const removeImage = (imgUrl: string) => {
    updateImages((prev) => prev.filter((url) => url !== imgUrl));
  };

  const handleGenerateImages = async (request: XHSImageGenerationRequest) => {
    const slotIds = Array.from({ length: request.count }, () =>
      crypto.randomUUID(),
    );
    if (bound && batchId && postId) {
      startPostImageGeneration(batchId, postId, slotIds);
    } else {
      setPendingImageSlots(slotIds);
    }
    try {
      const urls = await generateXhsImages(request);
      if (bound && batchId && postId) {
        completePostImageGeneration(batchId, postId, urls);
      } else {
        setImages((previous) => mergeXhsImages(previous, urls));
      }
      toast.success(`已生成 ${urls.length} 张图片并添加到帖子`);
    } catch (error) {
      if (bound && batchId && postId) {
        clearPostImageGeneration(batchId, postId);
      }
      toast.error(error instanceof Error ? error.message : "图片生成失败");
    } finally {
      if (!bound) setPendingImageSlots([]);
    }
  };

  // Add hashtag
  const addHashtag = () => {
    const tag = newTag.trim().replace(/^#/, "");
    if (tag && !hashtags.includes(tag)) {
      setHashtags((prev) => [...prev, tag]);
    }
    setNewTag("");
  };

  // Remove hashtag
  const removeHashtag = (tag: string) => {
    setHashtags((prev) => prev.filter((t) => t !== tag));
  };

  const reportResult = (
    status: XHSPublishResultItem["status"],
    message?: string,
  ) => {
    reportXhsPublishResults(onAction, {
      source: "editor",
      batchId,
      results: [{ postId, title, deviceId, status, message }],
    });
  };

  // Publish via the shared helper (push images + dispatch task). The action
  // round-trip reports success/failure or an explicit unknown outcome, so the
  // bot can respond without executing the publish twice.
  const handlePublish = async () => {
    if (!deviceId) {
      const message = "请先选择一台在线设备";
      setPublish({ state: "error", message });
      reportResult("error", message);
      return;
    }
    const post = { title, content, images: displayedImages, hashtags };
    try {
      await publishXhsPost(deviceId, post, (phase) => {
        if (bound && batchId && postId) setRowStatus(batchId, postId, phase);
        setPublish({
          state: "publishing",
          step:
            phase === "waiting"
              ? "正在等待设备完成当前任务…"
              : phase === "pushing"
                ? "正在推送图片到手机相册…"
                : "正在发送发布任务到手机…",
        });
      });
      if (bound && batchId && postId) setRowStatus(batchId, postId, "success");
      setPublish({ state: "success" });
      reportResult("success", "手机端已完成发布");
    } catch (err) {
      const message = err instanceof Error ? err.message : "发布失败";
      if (err instanceof XhsPublishStatusUnknownError) {
        if (bound && batchId && postId)
          setRowStatus(batchId, postId, "unknown", message);
        setPublish({ state: "unknown", message });
        reportResult("unknown", message);
        return;
      }
      if (bound && batchId && postId)
        setRowStatus(batchId, postId, "error", message);
      setPublish({ state: "error", message });
      reportResult("error", message);
    }
  };

  return (
    <div
      className="xhs-editor"
      style={{
        // Flush inside the canvas node frame: no own radius/shadow (the node
        // chrome provides them) — avoids the double-border. Fills the node.
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        background: "#ffffff",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "12px 16px",
          borderBottom: "1px solid #e5e5e5",
          flexShrink: 0,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <svg
            aria-hidden="true"
            width="20"
            height="20"
            viewBox="0 0 24 24"
            fill="none"
            stroke="var(--color-xhs)"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M12 20h9" />
            <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
          </svg>
          <span
            style={{
              fontSize: 15,
              fontWeight: 600,
              color: "var(--color-text-heading)",
            }}
          >
            小红书内容编辑
          </span>
        </div>
      </div>

      {/* Content region — flex column so the post-content textarea can grow to
          fill the remaining editor height; footer (device + publish) stays
          pinned to the bottom of the editor. */}
      <div
        style={{
          flex: 1,
          minHeight: 0,
          overflowY: "auto",
          display: "flex",
          flexDirection: "column",
        }}
      >
        {/* Image upload grid (compact thumbnails — 50% size, 6 per row) */}
        <div style={{ padding: "12px 16px 0", flexShrink: 0 }}>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(64px, 1fr))",
              gap: 8,
            }}
          >
            {displayedImages.map((img) => (
              <div
                key={img}
                style={{
                  position: "relative",
                  aspectRatio: "1",
                  borderRadius: 8,
                  overflow: "hidden",
                  background: "#f5f5f5",
                }}
              >
                <img
                  src={img}
                  alt=""
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                  }}
                />
                <button
                  type="button"
                  onClick={() => removeImage(img)}
                  style={{
                    position: "absolute",
                    top: 4,
                    right: 4,
                    width: 20,
                    height: 20,
                    borderRadius: "50%",
                    background: "rgba(0,0,0,0.5)",
                    border: "none",
                    cursor: "pointer",
                    color: "#fff",
                    fontSize: 12,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  ×
                </button>
              </div>
            ))}
            <XHSImageGenerationPlaceholders
              slotIds={displayedPendingImageSlots}
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              style={{
                aspectRatio: "1",
                borderRadius: 8,
                border: "2px dashed #d9d9d9",
                background: "#fafafa",
                cursor: "pointer",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                gap: 3,
                color: "#999",
                fontSize: 11,
              }}
            >
              <svg
                aria-hidden="true"
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
              >
                <path d="M12 5v14M5 12h14" />
              </svg>
              添加图片
            </button>
            <button
              ref={imageGenerationAnchorRef}
              type="button"
              onClick={() => setImageGenerationOpen(true)}
              disabled={displayedPendingImageSlots.length > 0}
              title="AI 生成图片"
              style={{
                aspectRatio: "1",
                borderRadius: 8,
                border: "1px solid #f2b8c4",
                background: "#fff4f6",
                cursor:
                  displayedPendingImageSlots.length > 0
                    ? "not-allowed"
                    : "pointer",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                gap: 3,
                color: "var(--color-xhs)",
                fontSize: 11,
                opacity: displayedPendingImageSlots.length > 0 ? 0.55 : 1,
              }}
            >
              <Sparkles size={18} aria-hidden="true" />
              AI 生图
            </button>
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              multiple
              onChange={(e) => handleImageUpload(e.target.files)}
              style={{ display: "none" }}
            />
          </div>
        </div>

        {/* Title input */}
        <div style={{ padding: "12px 16px 0", flexShrink: 0 }}>
          <div style={{ position: "relative" }}>
            <input
              type="text"
              value={title}
              onChange={(e) =>
                setTitle(e.target.value.slice(0, maxTitleLength))
              }
              placeholder="填写标题，更有吸引力"
              maxLength={maxTitleLength}
              style={{
                width: "100%",
                padding: "8px 12px",
                border: "1px solid #e5e5e5",
                borderRadius: 8,
                fontSize: 14,
                outline: "none",
                color: "var(--color-text-primary)",
                boxSizing: "border-box",
              }}
            />
            <span
              style={{
                position: "absolute",
                right: 12,
                top: "50%",
                transform: "translateY(-50%)",
                fontSize: 12,
                color: "#999",
              }}
            >
              {title.length}/{maxTitleLength}
            </span>
          </div>
        </div>

        {/* Content textarea — keeps a readable intrinsic height in inline chat
            surfaces and still grows inside fixed-height sidebar/canvas hosts. */}
        <div
          style={{
            padding: "8px 16px 0",
            flex: "1 0 220px",
            minHeight: 220,
            display: "flex",
            flexDirection: "column",
          }}
        >
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            placeholder="在这里分享你的故事..."
            style={{
              flex: 1,
              minHeight: 220,
              width: "100%",
              padding: "8px 12px",
              border: "1px solid #e5e5e5",
              borderRadius: 8,
              fontSize: 14,
              outline: "none",
              resize: "none",
              color: "var(--color-text-primary)",
              boxSizing: "border-box",
              fontFamily: "inherit",
            }}
          />
        </div>

        {/* Hashtags section */}
        <div style={{ padding: "16px 16px 0", flexShrink: 0 }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              flexWrap: "wrap",
            }}
          >
            <span
              style={{
                fontSize: 12,
                color: "var(--color-text-secondary)",
                fontWeight: 500,
              }}
            >
              话题
            </span>
            {hashtags.map((tag) => (
              <span
                key={tag}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "4px 10px",
                  borderRadius: 6,
                  background: "var(--color-xhs-wash)",
                  color: "var(--color-xhs)",
                  fontSize: 12,
                }}
              >
                #{tag}
                <button
                  type="button"
                  onClick={() => removeHashtag(tag)}
                  style={{
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    padding: 0,
                    color: "var(--color-xhs)",
                    opacity: 0.6,
                    fontSize: 12,
                    lineHeight: 1,
                  }}
                >
                  ×
                </button>
              </span>
            ))}
            <div
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 4,
              }}
            >
              <input
                ref={tagInputRef}
                type="text"
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                onKeyDown={(e) => {
                  // Enter mid-composition picks the IME candidate, not the tag.
                  if (e.key === "Enter" && !isImeComposing(e)) {
                    e.preventDefault();
                    addHashtag();
                  }
                }}
                placeholder="输入话题"
                style={{
                  width: 80,
                  padding: "2px 6px",
                  border: "1px solid #e5e5e5",
                  borderRadius: 4,
                  fontSize: 12,
                  outline: "none",
                  color: "var(--color-text-primary)",
                }}
              />
              <button
                type="button"
                onClick={addHashtag}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  height: 28,
                  background: "#fff",
                  border: "1px solid var(--color-border-strong)",
                  borderRadius: 6,
                  padding: "0 12px",
                  cursor: "pointer",
                  color: "var(--color-text-primary)",
                  fontSize: 12,
                  fontWeight: 500,
                }}
              >
                + 话题
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Footer: device selector + publish */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: 12,
          flexWrap: "wrap",
          padding: "14px 20px",
          borderTop: "1px solid var(--color-border-subtle)",
          flexShrink: 0,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            flex: "1 1 200px",
            minWidth: 0,
          }}
        >
          <span
            style={{
              fontSize: 12,
              color: "var(--color-text-secondary)",
              whiteSpace: "nowrap",
            }}
          >
            发布到
          </span>
          <select
            value={deviceId}
            onChange={(e) => setDeviceId(e.target.value)}
            style={{
              flex: 1,
              minWidth: 0,
              padding: "6px 8px",
              border: "1px solid #e5e5e5",
              borderRadius: 6,
              fontSize: 12,
              color: "var(--color-text-primary)",
              background: "#fff",
              outline: "none",
            }}
          >
            {devices.length === 0 ? (
              <option value="">无在线设备</option>
            ) : (
              devices.map((d: { deviceId: string; name?: string }) => (
                <option key={d.deviceId} value={d.deviceId}>
                  {d.name || d.deviceId}
                </option>
              ))
            )}
          </select>
        </div>
        <button
          type="button"
          onClick={() => {
            void handlePublish();
          }}
          disabled={
            publish.state === "publishing" || devices.length === 0 || !deviceId
          }
          style={{
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            height: "var(--a2ui-control-lg)",
            padding: "0 24px",
            borderRadius: 10,
            border: "none",
            background: "var(--color-xhs)",
            opacity:
              publish.state === "publishing" || devices.length === 0 ? 0.38 : 1,
            cursor:
              publish.state === "publishing" || devices.length === 0
                ? "not-allowed"
                : "pointer",
            fontSize: 14,
            color: "#fff",
            fontWeight: 600,
            whiteSpace: "nowrap",
            flex: "1 1 auto",
          }}
        >
          {publish.state === "publishing" ? "发布中…" : "发布"}
        </button>
      </div>

      {/* Status line. The red belongs to the channel (icon, topics, 发布);
          failure is the design system's error colour, so the two stop
          meaning the same thing. */}
      {publish.state !== "idle" && (
        <div style={{ padding: "0 20px 16px", flexShrink: 0 }}>
          <StatusPill
            tone={PUBLISH_TONE[publish.state]}
            className={
              publish.state === "error" || publish.state === "unknown"
                ? "a2ui-status-pill--wrap"
                : undefined
            }
          >
            {publish.state === "publishing" && publish.step}
            {publish.state === "success" && "手机端已完成发布"}
            {publish.state === "unknown" &&
              `发布结果待确认：${publish.message}`}
            {publish.state === "error" && publish.message}
          </StatusPill>
        </div>
      )}

      <XHSImageGenerationPopover
        open={imageGenerationOpen}
        anchorRef={imageGenerationAnchorRef}
        onOpenChange={setImageGenerationOpen}
        onGenerate={(request) => void handleGenerateImages(request)}
        postContext={{ title, content, hashtags }}
      />
    </div>
  );
}
