import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { type OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import type { GenerateImageRequest, GenerateVideoRequest } from "@nexu/shared";
import {
  describeImageRequestSchema,
  describeImageResponseSchema,
  enhanceImageRequestSchema,
  enhanceImageResponseSchema,
  generateAudioRequestSchema,
  generateAudioResponseSchema,
  generateImageRequestSchema,
  generateImageResponseSchema,
  generateTextRequestSchema,
  generateTextResponseSchema,
  generateVideoRequestSchema,
  generateVideoResponseSchema,
  imageGenerationJobSchema,
  saveInboundImageRequestSchema,
  saveInboundImageResponseSchema,
  videoGenerationJobSchema,
} from "@nexu/shared";
import type { ControllerContainer } from "../app/container.js";
import { logger } from "../lib/logger.js";
import {
  mediaCacheDir,
  mediaCachePathFor,
  resolveMediaFileWithinRoot,
} from "../lib/media-cache.js";
import {
  MediaGenerationJobService,
  MediaGenerationQueueFullError,
} from "../services/media-generation-job-service.js";
import {
  ImageGenerationFailedError,
  InvalidMediaReferenceError,
} from "../services/media-generation-service.js";
import type { ControllerBindings } from "../types.js";

/**
 * Map an unexpected media-generation error to a graceful 502. Known failures
 * (ImageGenerationFailedError → 502, InvalidMediaReferenceError → 400) are
 * handled at each call site; this catch-all covers anything else — a runtime
 * hiccup (e.g. the utility agent missing from the openclaw config, a WS drop) —
 * so the route degrades per the "502 = generation failed" contract instead of
 * leaking a 500 with internal detail (agent ids, paths). The raw error is
 * logged server-side for debugging; the client sees a generic message.
 */
function mediaGenerationFailure(error: unknown): { message: string } {
  logger.error({ err: error }, "media generation: unexpected failure");
  return { message: "生成失败，请稍后重试" };
}

const MEDIA_EXTENSION_MIME: Record<string, string> = {
  ".webp": "image/webp",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".pdf": "application/pdf",
  ".doc": "application/msword",
  ".docx":
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".xls": "application/vnd.ms-excel",
  ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".ppt": "application/vnd.ms-powerpoint",
  ".pptx":
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

// ── prompt-cover generation ────────────────────────────────────────────────
// Library prompts without an upstream cover get one generated by OUR image
// backend, persisted to disk keyed by the prompt's library id — one
// generation per prompt ever. Requests dedupe per id and run through a
// serial chain so a page of coverless cards can't stampede the generation
// backend.

/** Library ids are slug-shaped; the leading alnum + no dots keeps them path-safe. */
const GENERATED_COVER_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,119}$/;

const promptCoverGenerateRequestSchema = z.object({
  id: z.string().regex(GENERATED_COVER_ID),
  prompt: z.string().min(1).max(4000),
});
const promptCoverGenerateResponseSchema = z.object({
  /** Servable URL of the generated cover (GET /media/prompt-cover-generated). */
  url: z.string(),
});

/**
 * Negative cache for cover-proxy origin failures: a hanging/unreachable
 * origin (e.g. a blocked CDN) must fail FAST on re-request instead of
 * re-hanging a browser connection slot on every dialog open.
 */
const coverFetchFailures = new Map<string, number>();
const COVER_FAILURE_TTL_MS = 10 * 60 * 1000;

const generatedCoverInFlight = new Map<string, Promise<string>>();
let generatedCoverChain: Promise<unknown> = Promise.resolve();

function generatedCoverPaths(nexuHomeDir: string, id: string) {
  const dir = path.join(nexuHomeDir, "prompt-covers-generated");
  return {
    dir,
    dataPath: path.join(dir, id),
    metaPath: path.join(dir, `${id}.json`),
    servedUrl: `/api/v1/media/prompt-cover-generated?id=${encodeURIComponent(id)}`,
  };
}

export function registerMediaRoutes(
  app: OpenAPIHono<ControllerBindings>,
  container: ControllerContainer,
): void {
  const imageGenerationJobs = new MediaGenerationJobService({
    label: "图片生成",
    run: (input: GenerateImageRequest) =>
      container.mediaGenerationService.generateImage(input),
  });
  // Video takes minutes, so the canvas submits a job, persists its id, and can
  // pick the poll back up after a page reload instead of losing the run.
  const videoGenerationJobs = new MediaGenerationJobService({
    label: "视频生成",
    run: (input: GenerateVideoRequest) =>
      container.mediaGenerationService.generateVideo(input),
  });

  // The desktop uses this task API so slow image generation no longer keeps a
  // renderer request open. The synchronous endpoint below remains available
  // for compatibility with older clients and prompt-cover generation.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/image-jobs",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateImageRequestSchema },
          },
        },
      },
      responses: {
        202: {
          content: {
            "application/json": { schema: imageGenerationJobSchema },
          },
          description: "Image generation job accepted",
        },
        429: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Image generation queue is full",
        },
      },
    }),
    (c) => {
      try {
        return c.json(imageGenerationJobs.submit(c.req.valid("json")), 202);
      } catch (error) {
        if (error instanceof MediaGenerationQueueFullError) {
          return c.json({ message: error.message }, 429);
        }
        throw error;
      }
    },
  );

  app.openapi(
    createRoute({
      method: "get",
      path: "/api/v1/media/image-jobs/{jobId}",
      tags: ["Media"],
      request: {
        params: z.object({ jobId: z.string().uuid() }),
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: imageGenerationJobSchema },
          },
          description: "Current image generation job state",
        },
        404: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Image generation job not found or expired",
        },
      },
    }),
    (c) => {
      const job = imageGenerationJobs.get(c.req.valid("param").jobId);
      if (!job) return c.json({ message: "图片生成任务不存在或已过期" }, 404);
      return c.json(job, 200);
    },
  );

  // POST /api/v1/media/generate-image — prompt-to-image for the canvas
  // workbench (S7). Drives the OpenClaw image_generate agent tool over a
  // utility subagent lane; the result is served by /media/state-file below.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/generate-image",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateImageRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: generateImageResponseSchema },
          },
          description: "Image generated and servable via /media/state-file",
        },
        400: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Invalid reference image path",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Generation failed or timed out",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result = await container.mediaGenerationService.generateImage({
          prompt: input.prompt,
          referenceImages: input.referenceImages,
          count: input.count,
          sourceImage: input.sourceImage,
          maskDataUrl: input.maskDataUrl,
          model: input.model,
          quality: input.quality,
          aspectRatio: input.aspectRatio,
          size: input.size,
          transparentBackground: input.transparentBackground,
        });
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof InvalidMediaReferenceError) {
          return c.json({ message: error.message }, 400);
        }
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/video-jobs",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateVideoRequestSchema },
          },
        },
      },
      responses: {
        202: {
          content: {
            "application/json": { schema: videoGenerationJobSchema },
          },
          description: "Video generation job accepted",
        },
        429: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Video generation queue is full",
        },
      },
    }),
    (c) => {
      try {
        return c.json(videoGenerationJobs.submit(c.req.valid("json")), 202);
      } catch (error) {
        if (error instanceof MediaGenerationQueueFullError) {
          return c.json({ message: error.message }, 429);
        }
        throw error;
      }
    },
  );

  app.openapi(
    createRoute({
      method: "get",
      path: "/api/v1/media/video-jobs/{jobId}",
      tags: ["Media"],
      request: {
        params: z.object({ jobId: z.string().uuid() }),
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: videoGenerationJobSchema },
          },
          description: "Current video generation job state",
        },
        404: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Video generation job not found or expired",
        },
      },
    }),
    (c) => {
      const job = videoGenerationJobs.get(c.req.valid("param").jobId);
      if (!job) return c.json({ message: "视频生成任务不存在或已过期" }, 404);
      return c.json(job, 200);
    },
  );

  // POST /api/v1/media/generate-video — bundled Tabby adapter with a utility
  // subagent fallback for explicitly selected third-party models.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/generate-video",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateVideoRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: generateVideoResponseSchema },
          },
          description: "Video generated and servable via /media/state-file",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Generation failed or timed out (including UNAVAILABLE)",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result = await container.mediaGenerationService.generateVideo({
          prompt: input.prompt,
          durationSeconds: input.durationSeconds,
          resolution: input.resolution,
          model: input.model,
          aspectRatio: input.aspectRatio,
          numFrames: input.numFrames,
          frameRate: input.frameRate,
          numInferenceSteps: input.numInferenceSteps,
          negativePrompt: input.negativePrompt,
          seed: input.seed,
          generateAudio: input.generateAudio,
          watermark: input.watermark,
        });
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // POST /api/v1/media/generate-audio — UNAVAILABLE-first audio/TTS generation.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/generate-audio",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateAudioRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: generateAudioResponseSchema },
          },
          description: "Audio generated and servable via /media/state-file",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Generation failed or timed out (including UNAVAILABLE)",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result = await container.mediaGenerationService.generateAudio({
          prompt: input.prompt,
          voice: input.voice,
          speed: input.speed,
          model: input.model,
          format: input.format,
          instructions: input.instructions,
        });
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // POST /api/v1/media/enhance-image — UNAVAILABLE-first image enhancement
  // (super-resolve / multi-angle). Ships before backend skills land.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/enhance-image",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: enhanceImageRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: enhanceImageResponseSchema },
          },
          description: "Image enhanced and servable via /media/state-file",
        },
        400: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Invalid source image path",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description:
            "Enhancement failed or timed out (including UNAVAILABLE)",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result =
          await container.mediaGenerationService.enhanceImage(input);
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof InvalidMediaReferenceError) {
          return c.json({ message: error.message }, 400);
        }
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // POST /api/v1/media/describe-image — UNAVAILABLE-first reverse-prompt
  // (generate a text-to-image prompt from an existing image). May work today
  // with vision-capable models.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/describe-image",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: describeImageRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: describeImageResponseSchema },
          },
          description: "Image described — returns a text-to-image prompt",
        },
        400: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Invalid source image path",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description:
            "Description failed or timed out (including UNAVAILABLE)",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result =
          await container.mediaGenerationService.describeImage(input);
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof InvalidMediaReferenceError) {
          return c.json({ message: error.message }, 400);
        }
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // POST /api/v1/media/inbound-image — persist a canvas-composed PNG so it can
  // be handed back as a `referenceImages` entry (those must be absolute paths
  // under the media dir; a data URL is rejected).
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/inbound-image",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: saveInboundImageRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: saveInboundImageResponseSchema },
          },
          description: "Image saved into the inbound media dir",
        },
        400: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Invalid image data",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result =
          await container.mediaGenerationService.saveInboundImage(input);
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof InvalidMediaReferenceError) {
          return c.json({ message: error.message }, 400);
        }
        throw error;
      }
    },
  );

  // POST /api/v1/media/generate-text — write or rewrite text via the utility
  // lane. UNAVAILABLE-first; works today with any chat-capable model.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/generate-text",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: generateTextRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: generateTextResponseSchema },
          },
          description: "Text generated — returns the resulting text",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description:
            "Text generation failed or timed out (including UNAVAILABLE)",
        },
      },
    }),
    async (c) => {
      const input = c.req.valid("json");
      try {
        const result =
          await container.mediaGenerationService.generateText(input);
        return c.json(result, 200);
      } catch (error) {
        if (error instanceof ImageGenerationFailedError) {
          return c.json({ message: error.message }, 502);
        }
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // Serves media files referenced by chat transcripts (user uploads under
  // media/inbound, generated images under media/tool-image-generation, …).
  // Plain app.get like the screenshots route below: the response is binary
  // consumed by <img> tags, not the generated SDK.
  app.get("/api/v1/media/state-file", async (c) => {
    const rawPath = c.req.query("path");
    if (!rawPath) {
      return c.text("Not found", 404);
    }
    // Only regular files whose canonical path stays inside the OpenClaw state
    // media directory are reachable. This rejects symlink escapes as well as
    // lexical path traversal.
    const mediaRoot = path.resolve(container.env.openclawStateDir, "media");
    const resolved = path.resolve(rawPath);
    const resolution = await resolveMediaFileWithinRoot(mediaRoot, resolved);
    if (resolution.status === "unsafe") {
      return c.text("Not found", 404);
    }
    const mime =
      MEDIA_EXTENSION_MIME[path.extname(resolved).toLowerCase()] ??
      "application/octet-stream";
    const serve = (data: Buffer<ArrayBuffer>) =>
      c.body(data, 200, {
        "Content-Type": mime,
        "Cache-Control": "private, max-age=3600",
      });
    try {
      if (resolution.status === "file") {
        return serve(await readFile(resolution.realPath));
      }
      throw new Error("source media file is missing");
    } catch {
      // Original was TTL-cleaned by OpenClaw — fall back to the durable
      // mirror captured at history-read time (see sessions-runtime).
      try {
        return serve(
          await readFile(
            mediaCachePathFor(
              mediaCacheDir(container.env.nexuHomeDir),
              resolved,
            ),
          ),
        );
      } catch {
        return c.text("Not found", 404);
      }
    }
  });

  app.get("/api/v1/media/screenshots/:filename", async (c) => {
    const filename = c.req.param("filename");
    if (!filename || filename.includes("..")) {
      return c.text("Not found", 404);
    }
    const filePath = path.join(container.env.screenshotsDir, filename);
    try {
      const data = await readFile(filePath);
      const ext = path.extname(filename).toLowerCase();
      const mime =
        ext === ".webp"
          ? "image/webp"
          : ext === ".png"
            ? "image/png"
            : "image/jpeg";
      return c.body(data, 200, {
        "Content-Type": mime,
        "Cache-Control": "public, max-age=3600",
      });
    } catch {
      return c.text("Not found", 404);
    }
  });

  // GET /api/v1/media/prompt-cover?url=… — disk-backed cache proxy for
  // prompt-library cover images. The web app's library data references
  // covers on GitHub/Twitter CDNs; routing them through here means each
  // image is fetched from the origin ONCE ever, then served locally.
  // Plain app.get like state-file above: binary responses aren't
  // SDK-consumable, so they stay off the OpenAPI spec.
  app.get("/api/v1/media/prompt-cover", async (c) => {
    const rawUrl = c.req.query("url");
    if (!rawUrl) return c.text("Not found", 404);
    let parsed: URL;
    try {
      parsed = new URL(rawUrl);
    } catch {
      return c.text("Not found", 404);
    }
    // SSRF gate: https-only, and only the hosts the prompt sources actually
    // use. Never proxy arbitrary URLs.
    const hostAllowed =
      parsed.hostname === "github.com" ||
      parsed.hostname === "pbs.twimg.com" ||
      parsed.hostname.endsWith(".githubusercontent.com");
    if (parsed.protocol !== "https:" || !hostAllowed) {
      return c.text("Not found", 404);
    }

    const cacheDir = path.join(container.env.nexuHomeDir, "prompt-covers");
    const hash = createHash("sha256").update(rawUrl).digest("hex");
    const dataPath = path.join(cacheDir, hash);
    const metaPath = path.join(cacheDir, `${hash}.json`);
    const serve = (data: Buffer<ArrayBuffer>, contentType: string) =>
      c.body(data, 200, {
        "Content-Type": contentType,
        "Cache-Control": "public, max-age=604800",
      });

    // Cache hit — covers are immutable in practice, no TTL.
    try {
      const [data, metaRaw] = await Promise.all([
        readFile(dataPath),
        readFile(metaPath, "utf8"),
      ]);
      const meta = JSON.parse(metaRaw) as { contentType?: string };
      return serve(data, meta.contentType ?? "application/octet-stream");
    } catch {
      // miss — fall through to the origin fetch
    }

    // Recently failed origin → fail fast (negative cache).
    const failedAt = coverFetchFailures.get(rawUrl);
    if (
      failedAt !== undefined &&
      Date.now() - failedAt < COVER_FAILURE_TTL_MS
    ) {
      return c.text("Bad gateway", 502);
    }

    try {
      const response = await fetch(rawUrl, {
        signal: AbortSignal.timeout(6_000),
      });
      if (!response.ok) return c.text("Not found", 404);
      const contentType = response.headers.get("content-type") ?? "";
      if (!contentType.startsWith("image/")) return c.text("Not found", 404);
      const data = Buffer.from(await response.arrayBuffer());
      // 10 MB cap — a cover should be a few hundred KB; anything bigger is
      // not worth caching to the user's disk.
      if (data.byteLength > 10 * 1024 * 1024) return c.text("Not found", 404);
      // Best-effort cache write; serving must not depend on disk success.
      try {
        await mkdir(cacheDir, { recursive: true });
        await writeFile(dataPath, data);
        await writeFile(metaPath, JSON.stringify({ contentType }));
      } catch (error) {
        logger.warn({ err: error }, "prompt-cover: cache write failed");
      }
      return serve(data, contentType);
    } catch (error) {
      coverFetchFailures.set(rawUrl, Date.now());
      logger.warn({ err: error }, "prompt-cover: origin fetch failed");
      return c.text("Bad gateway", 502);
    }
  });

  // POST /api/v1/media/prompt-cover-generate — generate (once) a preview
  // cover for a library prompt that has none, via our own image backend.
  app.openapi(
    createRoute({
      method: "post",
      path: "/api/v1/media/prompt-cover-generate",
      tags: ["Media"],
      request: {
        body: {
          content: {
            "application/json": { schema: promptCoverGenerateRequestSchema },
          },
        },
      },
      responses: {
        200: {
          content: {
            "application/json": { schema: promptCoverGenerateResponseSchema },
          },
          description:
            "Cover ready (generated now or cached from an earlier call)",
        },
        502: {
          content: {
            "application/json": { schema: z.object({ message: z.string() }) },
          },
          description: "Generation failed or timed out",
        },
      },
    }),
    async (c) => {
      const { id, prompt } = c.req.valid("json");
      const { dir, dataPath, metaPath, servedUrl } = generatedCoverPaths(
        container.env.nexuHomeDir,
        id,
      );

      // Already on disk → instant.
      try {
        await readFile(dataPath);
        return c.json({ url: servedUrl }, 200);
      } catch {
        // not cached — fall through to generation
      }

      let job = generatedCoverInFlight.get(id);
      if (!job) {
        const run = async (): Promise<string> => {
          // An earlier queued job for the same prompt may have finished
          // while this one waited its turn in the chain.
          try {
            await readFile(dataPath);
            return servedUrl;
          } catch {
            // still missing — generate
          }
          const result = await container.mediaGenerationService.generateImage({
            // The library prompt IS an image prompt — use it directly,
            // truncated; cheapest quality, covers are thumbnails.
            prompt: prompt.slice(0, 600),
            count: 1,
            quality: "low",
            aspectRatio: "1:1",
          });
          const image = await readFile(result.path);
          const contentType =
            MEDIA_EXTENSION_MIME[path.extname(result.path).toLowerCase()] ??
            "image/png";
          await mkdir(dir, { recursive: true });
          await writeFile(dataPath, image);
          await writeFile(metaPath, JSON.stringify({ contentType }));
          return servedUrl;
        };
        // Serial chain: one generation at a time regardless of how many
        // coverless cards are on screen. A failed predecessor must not
        // poison the queue (second arg runs on rejection too).
        const queued = generatedCoverChain.then(run, run);
        generatedCoverChain = queued.catch(() => {});
        job = queued.finally(() => generatedCoverInFlight.delete(id));
        generatedCoverInFlight.set(id, job);
      }

      try {
        return c.json({ url: await job }, 200);
      } catch (error) {
        return c.json(mediaGenerationFailure(error), 502);
      }
    },
  );

  // GET /api/v1/media/prompt-cover-generated?id=… — serve a generated cover
  // from the disk cache. Plain app.get: binary, not SDK-consumable.
  app.get("/api/v1/media/prompt-cover-generated", async (c) => {
    const id = c.req.query("id");
    if (!id || !GENERATED_COVER_ID.test(id)) return c.text("Not found", 404);
    const { dataPath, metaPath } = generatedCoverPaths(
      container.env.nexuHomeDir,
      id,
    );
    try {
      const [data, metaRaw] = await Promise.all([
        readFile(dataPath),
        readFile(metaPath, "utf8"),
      ]);
      const meta = JSON.parse(metaRaw) as { contentType?: string };
      return c.body(data, 200, {
        "Content-Type": meta.contentType ?? "image/png",
        "Cache-Control": "public, max-age=604800",
      });
    } catch {
      return c.text("Not found", 404);
    }
  });
}
